name: Feature request
description: Propose an improvement to Quaid
title: "[feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What pain point are you solving?
      placeholder: Describe the current limitation.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What should Quaid do?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What else did you consider?

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Retrieval
        - Extraction
        - Janitor
        - OpenClaw adapter
        - MCP/CLI
        - Docs
        - Test infra
        - Installer

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I can help implement this.
